#!/usr/bin/env python3
"""
Fast board renderer using pre-rendered assets.

Composites letter tiles onto pre-rendered board background for fast rendering.
Uses board_assets/ generated by generate_board_assets.py.

Usage:
    python3 fast_render_board.py "cgp_string" output.png
    python3 fast_render_board.py --labels "cgp_string" output.png
"""

import sys
from pathlib import Path
from PIL import Image

# Board dimensions (must match render_board.py)
BOARD_SIZE = 15
BASE_SQUARE_SIZE = 63  # At 1x scale (from render_board.py)
TILE_FRACTION = 0.88   # Tile size as fraction of square (from render_board.py)
TILE_SIZE = int(BASE_SQUARE_SIZE * TILE_FRACTION)  # 55 pixels
VIDEO_WIDTH = 1920
VIDEO_HEIGHT = 1080


def parse_cgp_board(cgp_string):
    """
    Parse CGP board representation.

    Returns:
        15x15 list of strings ('' for empty, 'A'-'Z' for letters, 'a'-'z' for blanks)
    """
    parts = cgp_string.strip().split()
    if not parts:
        raise ValueError("Empty CGP string")

    board_part = parts[0]
    rows = board_part.split('/')

    if len(rows) != BOARD_SIZE:
        raise ValueError(f"Expected {BOARD_SIZE} rows, got {len(rows)}")

    board = []
    for row_str in rows:
        row = []
        i = 0
        while i < len(row_str):
            char = row_str[i]
            if char.isdigit():
                # Number indicates empty squares - read full number
                num_str = ''
                while i < len(row_str) and row_str[i].isdigit():
                    num_str += row_str[i]
                    i += 1
                num_empty = int(num_str)
                row.extend([''] * num_empty)
                continue  # i already advanced
            else:
                # Letter (uppercase or lowercase for blank)
                row.append(char)
            i += 1

        if len(row) != BOARD_SIZE:
            raise ValueError(f"Row has {len(row)} squares, expected {BOARD_SIZE}: {row_str}")

        board.append(row)

    return board


def fast_render_board(cgp_string, output_path, with_labels=False, assets_dir="board_assets", bg_color=None):
    """
    Fast render a board by compositing pre-rendered assets.

    Args:
        cgp_string: CGP format position string
        output_path: Output PNG file path
        with_labels: If True, use labeled board background
        assets_dir: Directory containing board_assets
        bg_color: Optional RGB tuple for video background (default: white)
    """
    assets_path = Path(assets_dir)

    # Check if assets exist
    if not assets_path.exists():
        print(f"Error: Assets directory not found: {assets_path}", file=sys.stderr)
        print("Run: python3 video_tools/generate_board_assets.py board_assets", file=sys.stderr)
        sys.exit(1)

    # Load empty board background
    board_bg_name = "board_empty_labeled.png" if with_labels else "board_empty.png"
    board_bg_path = assets_path / board_bg_name

    if not board_bg_path.exists():
        print(f"Error: Board background not found: {board_bg_path}", file=sys.stderr)
        sys.exit(1)

    # Load board background
    board_bg = Image.open(board_bg_path)

    # Create video canvas with custom background color
    if bg_color is None:
        bg_color = (255, 255, 255)  # Default white

    # Create canvas and composite board onto it (simple, no transparency)
    canvas = Image.new('RGB', (VIDEO_WIDTH, VIDEO_HEIGHT), bg_color)

    # Center the board on the canvas
    board_x = (VIDEO_WIDTH - board_bg.width) // 2
    board_y = (VIDEO_HEIGHT - board_bg.height) // 2
    canvas.paste(board_bg, (board_x, board_y))

    board_img = canvas

    # Parse CGP to get board state
    board = parse_cgp_board(cgp_string)

    # Calculate board position on canvas
    # The render_board output is 998x998, centered on 1920x1080
    board_render_size = BOARD_SIZE * BASE_SQUARE_SIZE

    # Margins within the board image (matching render_board.py)
    if with_labels:
        margin_left = 40
        margin_top = 38
        margin_right = 13
        margin_bottom = 15
    else:
        margin_left = 40
        margin_top = 40
        margin_right = 40
        margin_bottom = 40

    board_img_size = board_render_size + margin_left + margin_right

    # Where the board image is placed on the video canvas
    board_canvas_x = (VIDEO_WIDTH - board_img_size) // 2
    board_canvas_y = (VIDEO_HEIGHT - board_img_size) // 2

    # Where the playing area starts (within the video canvas)
    playing_area_x = board_canvas_x + margin_left
    playing_area_y = board_canvas_y + margin_top

    # Composite letter tiles
    # Tiles are now BASE_SQUARE_SIZE x BASE_SQUARE_SIZE with centering baked in
    tiles_path = assets_path / "tiles"
    tile_count = 0
    for row in range(BOARD_SIZE):
        for col in range(BOARD_SIZE):
            letter = board[row][col]
            if letter:  # Has a letter
                # Determine tile filename
                if letter.islower():
                    tile_filename = f"blank_{letter}.png"
                else:
                    tile_filename = f"letter_{letter}.png"

                tile_path = tiles_path / tile_filename
                if not tile_path.exists():
                    print(f"Warning: Tile not found: {tile_path}", file=sys.stderr)
                    continue

                # Load tile and paste onto board
                tile = Image.open(tile_path)
                # Calculate position on video canvas - no offset needed, tiles have margin baked in
                x = playing_area_x + col * BASE_SQUARE_SIZE
                y = playing_area_y + row * BASE_SQUARE_SIZE
                board_img.paste(tile, (x, y))  # No mask needed - tiles have white background baked in
                tile_count += 1

    # Save result
    board_img.save(output_path)
    print(f"Rendered {tile_count} tiles to {output_path}")


def main():
    """Main entry point."""
    args = sys.argv[1:]

    if len(args) == 0:
        print("Usage: python3 fast_render_board.py [--labels] <cgp_string> <output.png>")
        print()
        print("Example:")
        print('  python3 fast_render_board.py "15/15/15/7STEARIN/15/15/15/15/15/15/15/15/15/15/15 ABCDEFG/ 0/0 0" board.png')
        sys.exit(1)

    # Parse options
    with_labels = False
    bg_color = None

    while args and args[0].startswith('--'):
        if args[0] == '--labels':
            with_labels = True
            args = args[1:]
        elif args[0] == '--bg':
            if len(args) < 2:
                print("Error: --bg requires R,G,B argument", file=sys.stderr)
                sys.exit(1)
            try:
                r, g, b = map(int, args[1].split(','))
                bg_color = (r, g, b)
            except:
                print("Error: Invalid --bg format. Use R,G,B like: 128,0,128", file=sys.stderr)
                sys.exit(1)
            args = args[2:]
        else:
            break

    if len(args) < 2:
        print("Error: Missing CGP string or output path", file=sys.stderr)
        sys.exit(1)

    cgp_string = args[0]
    output_path = args[1]

    print("Fast Board Renderer")
    print("=" * 60)
    print(f"CGP: {cgp_string[:60]}{'...' if len(cgp_string) > 60 else ''}")
    print(f"Output: {output_path}")
    print(f"Labels: {with_labels}")
    print(f"Background: RGB{bg_color if bg_color else '(255, 255, 255)'}")
    print()

    # Render
    fast_render_board(cgp_string, output_path, with_labels, bg_color=bg_color)


if __name__ == "__main__":
    main()
